### PR TITLE
Adds module export

### PR DESCRIPTION
**Pull request by cerisier**
For usage with ES6

### CODE REVIEW

**Comment by grillorafael** [comment]
Hi @cerisier. Can you embed on this PR the fix for Travis?

It is related to chrome address for travis. 

See this http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

**Comment by pocketjoso** [comment]
Waiting for this PR to. Will this fix work with the extra `TYPE` assignment at the bottom of the file, after the export? Will it be included?

@grillorafael would be much cleaner imo to declare the TYPE inside the class, not sure why it is outside. Separate PR perhaps.

**Comment by grillorafael** [comment]
Yes @pocketjoso 

This should probably be another PR. I created another issue #14 for talk about it.

**Comment by grillorafael** [comment]
Maybe it is better to check which module loader?

```javascript
// Node: Export function
if (typeof module !== "undefined" && module.exports) {
    module.exports = tinycolor;
}
// AMD/requirejs: Define the module
else if (typeof define === 'function' && define.amd) {
    define(function () {return tinycolor;});
}
// Browser: Expose to window
else {
    window.tinycolor = tinycolor;
}
```

Took this example from https://github.com/bgrins/TinyColor

**Comment by pocketjoso** [comment]
> Maybe it is better to check which module loader?

Babel will add necessary fallback support when you transpile your code to `es5`.

**Comment by grillorafael** [comment]
Great :)

**Comment by grillorafael** [comment]
I'll merge #12 today and free the other PR's

**Comment by grillorafael** [comment]
Ready to rebase

**Comment by grillorafael** [comment]
@cerisier can you make sure the example still works?

**Comment by grillorafael** [comment]
Already covered by https://github.com/commodityvectors/d3-timeline/pull/15

**Pull request closed without merging**
