### PR TITLE
Feature/custom class

### LINKED ISSUE #10: Configuration options
Are there any configuration options for changing the color of the bars or the background, etc.?

### PR DESCRIPTION
**Pull request by grillorafael**
Fix  #10

### CODE REVIEW

**Comment by grillorafael** [comment]
@pmpbar can you check if it is enough?

**Comment by grillorafael** [comment]
Hey @pmpbar Do you have any feedback?

**Comment by pmpbar** [comment]
Excellent! Exactly what I was looking for. You da man! (sorry for the late response, it was a long weekend here).

**Comment by grillorafael** [comment]
No worries mate. I'm going to start merging things to release `1.1.0` with #13 and #9

**Pull request merged**
