### PR TITLE
add intervalMinWidth option

### PR DESCRIPTION
**Pull request by pocketjoso**
Hi, thanks for writing this plugin!

I need to see the intervals on zoom out just as we can with the points, so I propose to add in a minWidth value for them. I set the default to `8px`, but perhaps you prefer the default to stick to the current behaviour (0px)?

### From
d3-timeline-chart-before

### To
d3-timeline-chart-after

### CODE REVIEW

**Comment by grillorafael** [comment]
Hi @pocketjoso !

Thanks for your PR. All seems good. It might be interesting as well to define a default minWidth as well? Maybe something like 5px ?

I'll just wait for #12 to be merged with the test fix (which are still pending to be written) to be able to merge this as well.

**Comment by grillorafael** [comment]
Just saw that you added 8px by default. Sorry on that :)


All good. Just waiting for #12 on the travis fix to be able to merge.

**Comment by pocketjoso** [comment]
Cheers.

Btw, you're package doesn't export anytthing, so cannot be used out of the box via package managers like `npm`. Since you're using es2015, you can fix this by simply adding a `export default TimlineChart` at the bottom of your JS file.

**Comment by grillorafael** [comment]
This is fixed on #9. When #12 is merged, I'll pack those 3 changes into a new minor version.

**Comment by grillorafael** [comment]
Ready to rebase

**Comment by grillorafael** [comment]
@pocketjoso Waiting on you now :)

**Comment by pocketjoso** [comment]
Sorry for delay - updated now.

**Comment by grillorafael** [comment]
Merged and published

**Comment by pocketjoso** [comment]
Awesome.

**Pull request merged**
